import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "react-hot-toast";
// import { ConfigProvider } from 'antd';



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        {/* <ConfigProvider direction="rtl"> */}
        {children}
        <Toaster />
        {/* </ConfigProvider> */}
      </body>
    </html>
  );
}
 